import "@/styles/globals.css";

export const metadata = {
  title: 'Todo List',
  description: 'Generated by Next.js and NextUI',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}